version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: coach
    ports:
      - '5532:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nest -d coach"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://nest:nest@db:5432/coach?schema=public"
      PORT: '3000'
      JWT_SECRET: "secretcoach"
      JWT_EXPIRES_IN: "1d"
      FRONT_URL: ${FRONT_URL}
      RESET_COOLDOWN_MINUTES: '5'
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: '587'
      MAIL_USER: recomiendameappcl@gmail.com
      MAIL_PASS: ${MAIL_PASS}
      MAIL_FROM: "Recomi√©ndame <no-reply@recomiendame.cl>"
      API_URL: "https://api-coach.recomiendameapp.cl"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: "gpt-4o-mini"
      OPENAI_TIMEOUT_MS: "80000"
      OPENAI_MAX_TOKENS: "500"
      OPENAI_CONCURRENCY: "4"
      OPENAI_PLAN_STYLE: "compact"
      OPENAI_LOG: "1"
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      # Push Notifications
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      # Notificaciones
      NOTIFICATIONS_ENABLED: "true"
      CRON_JOBS_ENABLED: "true"

volumes:
  pg_data:
